### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by andrewisen-tikab** [andrewisen-tikab/three-bcf#47]
## Latest roadmap

- [ ] Cleanup
- [ ] Fix bugs
- [ ] Test in production

~~List of things that remains. Note that not all features will be supported. For example, might skip comments~~

## Markup

- [x] IfcProject
- [x] Date
- [x] TopicType
- [x] TopicStatus
- [x] ModifiedDate
- [x] ModifiedAuthor
- [x] AssignedTo
- [x] Comments
- [x] Index
- [x] DueDate

##  Viewpoint
- [x] Selection
- [x] Visibility 
- [x] Exceptions
- [x] Coloring
- [x] Camera (FOV + Aspect Ratio)
- [x] Misc data (e.g. `OriginatingSystem`)

## Example

- [x] Issue Sorter
- [x] Issue Table

<img width="567" alt="image" src="https://github.com/andrewisen-tikab/three-bcf/assets/82031267/6bade530-409d-4c9d-97df-3e3e8998bb8f">
